"""Adiciona visibilidade individual para cards

Revision ID: 7096947caf50
Revises: b0dd27f494d2
Create Date: 2025-07-09 10:47:47.076393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7096947caf50'
down_revision = 'b0dd27f494d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldos_visibilidade', sa.JSON(), nullable=False))
        batch_op.drop_column('mostrar_saldos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mostrar_saldos', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('saldos_visibilidade')

    # ### end Alembic commands ###
