"""Renomeia coluna password para password_hash

Revision ID: b0dd27f494d2
Revises: f2d0ed9c25b9
Create Date: 2025-07-06 12:37:59.784024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0dd27f494d2'
down_revision = 'f2d0ed9c25b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('categorias_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['user_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('categorias_ibfk_1'), 'usuarios', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
