"""Altera regra de unicidade de categorias

Revision ID: e8ff94e34a89
Revises: 7096947caf50
Create Date: 2025-07-12 12:11:48.715682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ff94e34a89'
down_revision = '7096947caf50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('_user_id_nome_uc'))
        batch_op.create_unique_constraint('_user_id_nome_tipo_uc', ['user_id', 'nome', 'tipo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_constraint('_user_id_nome_tipo_uc', type_='unique')
        batch_op.create_index(batch_op.f('_user_id_nome_uc'), ['user_id', 'nome'], unique=True)

    # ### end Alembic commands ###
