"""Adiciona tabela de excecoes de transacoes

Revision ID: f2d0ed9c25b9
Revises: 53ff13aa2268
Create Date: 2025-07-04 13:06:01.307906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d0ed9c25b9'
down_revision = '53ff13aa2268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excecao_transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_excecao', sa.Date(), nullable=False),
    sa.Column('transacao_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacoes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transacao_id', 'data_excecao', name='_transacao_data_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('excecao_transacao')
    # ### end Alembic commands ###
